<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm</name>
   <tag></tag>
   <elementGuidId>6dccf7d4-37c0-449c-b3d5-f660b6833cc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ap-button.btn-medium.confirm-bookings-submit-button.ng-binding.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7401ba48-f394-4c83-9e33-ae6ab11f3afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ap-button btn-medium confirm-bookings-submit-button ng-binding ng-scope</value>
      <webElementGuid>46fc8c90-741d-4fa7-89c7-e9f7ec38ee00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>confirmBookings()</value>
      <webElementGuid>056b10e6-4715-48bf-ae1c-49193df947a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>guestDetails.$invalid</value>
      <webElementGuid>88883b23-4699-41e3-948c-fa8c534a8bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!paymentRequired</value>
      <webElementGuid>ea3fa91f-aa5d-4026-a39d-278f5c49d701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						Confirm
					</value>
      <webElementGuid>4b1abb37-49c1-4be8-9fdd-17215a040960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/span[@class=&quot;ng-scope&quot;]/ap-booking-app[@class=&quot;ng-scope&quot;]/div[@class=&quot;ap-ba-wrapper ng-scope embedded&quot;]/div[@class=&quot;ap-ba-container with-footer&quot;]/div[@class=&quot;ap-ba-content-wrapper&quot;]/div[@class=&quot;ap-ba-main-section&quot;]/div[@class=&quot;ap-ba-content&quot;]/ap-booking-app-step-confirm[@class=&quot;ap-ba-step-container ng-isolate-scope&quot;]/div[@class=&quot;ap-ba-step confirm-bookings-container&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;confirm-bookings-footer footer-non-multibooking-mode&quot;]/div[@class=&quot;confirm-bookings-buttons&quot;]/span[@class=&quot;confirm-bookings-submit-buttons-click-mask&quot;]/button[@class=&quot;ap-button btn-medium confirm-bookings-submit-button ng-binding ng-scope&quot;]</value>
      <webElementGuid>ea79bd50-fecd-4882-8390-56e9d3b41d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_EPOS  Online Ticketing System For Visi_99e627/iframe_shortcode_iframe entered lazyloaded</value>
      <webElementGuid>8e9e19ee-ca7b-4354-9604-49d59f8b98fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>25b1086e-762b-4425-b2d8-3112eab537dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
						Confirm
					' or . = '
						Confirm
					')]</value>
      <webElementGuid>7de0a513-4471-4a04-bd7c-1e7b842d5583</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
