<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm</name>
   <tag></tag>
   <elementGuidId>6dccf7d4-37c0-449c-b3d5-f660b6833cc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ap-button.btn-medium.confirm-bookings-submit-button.ng-binding.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a77c6a5-8c33-458b-a4fd-6adb98fe3bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ap-button btn-medium confirm-bookings-submit-button ng-binding ng-scope</value>
      <webElementGuid>a59b58e0-2c89-4c1b-be2f-748ff2143fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>confirmBookings()</value>
      <webElementGuid>825840d6-bb7e-4876-b068-30bdd89917bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>guestDetails.$invalid</value>
      <webElementGuid>ee3899d1-7105-4fd0-84c1-5d247d97f9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!paymentRequired</value>
      <webElementGuid>beffdf97-4409-4c4a-b59a-4b86e847f8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						Confirm
					</value>
      <webElementGuid>b05c31f6-b266-41b5-ad7a-6124dbf2a698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/span[@class=&quot;ng-scope&quot;]/ap-booking-app[@class=&quot;ng-scope&quot;]/div[@class=&quot;ap-ba-wrapper ng-scope embedded&quot;]/div[@class=&quot;ap-ba-container with-footer&quot;]/div[@class=&quot;ap-ba-content-wrapper&quot;]/div[@class=&quot;ap-ba-main-section&quot;]/div[@class=&quot;ap-ba-content&quot;]/ap-booking-app-step-confirm[@class=&quot;ap-ba-step-container ng-isolate-scope&quot;]/div[@class=&quot;ap-ba-step confirm-bookings-container&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;confirm-bookings-footer footer-non-multibooking-mode&quot;]/div[@class=&quot;confirm-bookings-buttons&quot;]/span[@class=&quot;confirm-bookings-submit-buttons-click-mask&quot;]/button[@class=&quot;ap-button btn-medium confirm-bookings-submit-button ng-binding ng-scope&quot;]</value>
      <webElementGuid>24be539c-31ca-490b-8b2c-076821aacb54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_EPOS  Online Ticketing System For Visi_99e627/iframe_shortcode_iframe entered lazyloaded</value>
      <webElementGuid>52db0c28-b6d4-49ec-bbf9-8e53f38ce5f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>07db6db0-c2f0-45c7-8f3b-b8c3a947dab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
						Confirm
					' or . = '
						Confirm
					')]</value>
      <webElementGuid>1fd85d84-1eb2-4980-8fed-2f4ef8d8e39b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
