<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_shortcode_iframe entered lazyloaded</name>
   <tag></tag>
   <elementGuidId>28c8595b-f131-44e5-bad0-c5b7ecb4ef06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='fluentform_23']/fieldset/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.shortcode_iframe.entered.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2dd0fb1e-abd3-4901-8c46-387804931942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>74ec31b8-617a-44ed-8098-00890fbdaaee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9f0fee4f-ab06-4b2b-a466-0f37bd9d7de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shortcode_iframe entered lazyloaded</value>
      <webElementGuid>39f68f86-1f53-49e6-869d-4aca581624f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://book.appointedd.com/app/64e4982d83068751300113ce</value>
      <webElementGuid>ac26dbe3-48c4-4ffd-b35f-8e37957a151f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>25c793c1-7359-4454-be76-4f48ec96efad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>52f07310-d7c6-43a5-8577-3910aa306732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rocket-lazyload</name>
      <type>Main</type>
      <value>fitvidscompatible</value>
      <webElementGuid>5245d31e-e740-41a6-8370-895e7e568349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://book.appointedd.com/app/64e4982d83068751300113ce</value>
      <webElementGuid>3c5ab7fb-707f-4ead-b3b9-eadc6d5f20e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>700934ea-c2f1-4cca-afb6-1bcb881135d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fluentform_23&quot;)/fieldset[1]/div[@class=&quot;ff-el-group&quot;]/iframe[@class=&quot;shortcode_iframe entered lazyloaded&quot;]</value>
      <webElementGuid>e9722e1d-6e08-4f7c-af32-f3a18a63717d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fluentform_23']/fieldset/div/iframe</value>
      <webElementGuid>259250e7-fcf3-44d7-96aa-53c507f05507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>67f8980f-2365-4e63-9f50-6fa440ecd095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://book.appointedd.com/app/64e4982d83068751300113ce']</value>
      <webElementGuid>7c323912-0f4b-4f2e-84c3-6198725101d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
