<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_shortcode_iframe entered lazyloaded</name>
   <tag></tag>
   <elementGuidId>28c8595b-f131-44e5-bad0-c5b7ecb4ef06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='fluentform_23']/fieldset/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.shortcode_iframe.entered.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>586594dd-ed95-43bb-a489-abf8ac4717c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>8f270d5e-e97b-465d-aa24-f66bd7072019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a8586de7-4426-4393-9e29-26670f233eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shortcode_iframe entered lazyloaded</value>
      <webElementGuid>617a7555-3673-4a64-ad08-c88abb0cde03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://book.appointedd.com/app/64e4982d83068751300113ce</value>
      <webElementGuid>d7c2663d-667e-466f-b976-3e6e023812ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>bf2286b7-76d5-4043-b5f9-fa64f1656ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>d8a7e65b-3376-4279-bcf0-6d4ebbaa0976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rocket-lazyload</name>
      <type>Main</type>
      <value>fitvidscompatible</value>
      <webElementGuid>988b8685-7b36-4106-9a22-acde2e7e18c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://book.appointedd.com/app/64e4982d83068751300113ce</value>
      <webElementGuid>303cfbaf-1959-401f-8bd1-0c653e93526d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>13b45205-ea76-4ead-aaa3-6a804ff92c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fluentform_23&quot;)/fieldset[1]/div[@class=&quot;ff-el-group&quot;]/iframe[@class=&quot;shortcode_iframe entered lazyloaded&quot;]</value>
      <webElementGuid>990fb474-0fa9-4082-af2a-b666c6baa9f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fluentform_23']/fieldset/div/iframe</value>
      <webElementGuid>26fba99b-e59e-4c2e-b4e0-691dad7a8d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6c7aeedd-5d19-4f16-b355-39164037793c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://book.appointedd.com/app/64e4982d83068751300113ce']</value>
      <webElementGuid>984fadd4-d011-437e-a623-43589025ca97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
