<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonmobile-toggle</name>
   <tag></tag>
   <elementGuidId>592ce4e6-6b25-477c-8cae-7f647c5b8427</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mobile-toggle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mobile-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>12ffeed9-c406-4212-88b6-6a202fa64639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobile-toggle</value>
      <webElementGuid>6463ff49-d9cb-4799-91e0-0a91fce431dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hamburger-menu</value>
      <webElementGuid>a31a6b62-a98a-4931-8bde-2b5ee6957ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Open navigation</value>
      <webElementGuid>0f2a9468-f429-4e67-b566-2a4cc6340ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;main-navigation&quot;]/div[@class=&quot;wrapper mauto&quot;]/button[@id=&quot;mobile-toggle&quot;]</value>
      <webElementGuid>cd216a20-2ac8-4b42-acaa-aeaabb2ce1bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mobile-toggle']</value>
      <webElementGuid>49648f6d-541b-45d0-b501-ab97ae0a4598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[2]/div/button</value>
      <webElementGuid>d4906ad3-29f6-40f3-b4e7-b95c1e835b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a87de82b-3e33-46df-ac74-44312f934ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'mobile-toggle']</value>
      <webElementGuid>7e9d7b46-cbe4-4b64-a3c6-c81ee63e8925</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
