<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Contact</name>
   <tag></tag>
   <elementGuidId>7bd22845-8eea-4e5a-96a0-959ba8b123d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-3625']/a/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-3625 > a > span.link-content > span.menu-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2248c0b4-3061-444b-87ec-05cd4af7ac55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-title</value>
      <webElementGuid>edfedbb1-aa5c-4cfe-9fad-5ba984bd77ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact</value>
      <webElementGuid>ba56c82b-972f-4b6b-9abd-93a7879c34c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-top-level-nav-1&quot;)/li[@id=&quot;menu-item-3625&quot;]/a[1]/span[@class=&quot;link-content&quot;]/span[@class=&quot;menu-title&quot;]</value>
      <webElementGuid>29872f1b-9e40-46ba-8dba-ce61d3a0c375</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-3625']/a/span/span</value>
      <webElementGuid>16847bd4-1896-40ce-acb2-57b454bb693a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li[2]/a/span/span</value>
      <webElementGuid>c6baf375-a95f-4fc3-ba21-29231816fddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Contact' or . = 'Contact')]</value>
      <webElementGuid>44133e23-dbfe-460e-a87c-f6fce22de745</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
