<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_message</name>
   <tag></tag>
   <elementGuidId>35d0a67f-6908-4e66-80e7-1b389e971e5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ff_4_message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ff_4_message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1a865705-2e3d-4c7c-a311-afc5f586d46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c6c8c081-1f47-4f0d-a30c-bd60dbae1e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d7f4474-69ba-4ff0-9cc5-1e60563184ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>178b2495-e855-43fb-a6b6-dbd124701a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ff_4_message</value>
      <webElementGuid>0aecdec7-8d10-4bb8-ba98-47e01856880c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-el-form-control</value>
      <webElementGuid>c3760116-6b05-487f-a65a-e948c7404ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>7eb709f4-a1a8-4580-bce3-5a378c71425a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>17034cb5-b3f6-4780-bbc3-ca185aa4d0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>849bec72-8ca1-4381-8d08-17b2726bd061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ff_4_message&quot;)</value>
      <webElementGuid>c6e1f2fe-fcd6-4e68-8289-1f5e3aa80d56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ff_4_message']</value>
      <webElementGuid>0643a933-a31f-4abb-8c95-aa474f1a7664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fluentform_4']/fieldset/div[5]/div[2]/textarea</value>
      <webElementGuid>d4fd3b46-3ebb-4e61-89fd-7020a89dd7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>41b04f75-f33f-4699-9135-1581b964460c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'message' and @id = 'ff_4_message']</value>
      <webElementGuid>81490101-0b91-40e8-88a6-eae3fb1f5441</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
