<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Contact</name>
   <tag></tag>
   <elementGuidId>7c822405-64c1-445d-9154-304f4762ecc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-1421']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-1421 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3403729d-8e0a-4134-a357-d5142d5a902a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://thehbpgroup.co.uk/365/contact/</value>
      <webElementGuid>8d54f59a-f65a-40b5-9540-d059f23120d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact</value>
      <webElementGuid>79c57871-ae73-46b4-bf08-6bd00d316624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-1421&quot;)/a[1]</value>
      <webElementGuid>197f50d9-83a4-4cc8-a937-a6204efc8839</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1421']/a</value>
      <webElementGuid>b567a9c6-92ef-42ce-8e17-88040d915298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Contact')])[2]</value>
      <webElementGuid>e1e798c3-0c7b-4ae9-9db7-e64fa38c3421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://thehbpgroup.co.uk/365/contact/')])[3]</value>
      <webElementGuid>4e068a85-d088-4590-b885-77c0559a0c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[2]/a</value>
      <webElementGuid>388a6db9-49c4-47b1-9510-0f475c573ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://thehbpgroup.co.uk/365/contact/' and (text() = 'Contact' or . = 'Contact')]</value>
      <webElementGuid>7eb0f87b-7d73-4348-a51e-054348e5185c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
