<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_shortcode_iframe entered lazyloaded</name>
   <tag></tag>
   <elementGuidId>6b01fd4c-9582-45fe-97b2-e4a40b22ebcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='fluentform_24']/fieldset/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.shortcode_iframe.entered.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3e075afc-d9d8-4fe7-a6c9-5a12e1ab104c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>f1f91a01-3ddd-472f-b194-e9be58bbfab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ab3a3d5c-ea64-44fe-a4e7-dab8825fbecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shortcode_iframe entered lazyloaded</value>
      <webElementGuid>808143ea-0f6e-4b2c-b001-5936e59db165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://book.appointedd.com/app/638e11d5802579cfe10684e0</value>
      <webElementGuid>b03ca680-d3c6-45b6-91a2-ce015537ad2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>8f0a50ce-8efd-4847-9775-913b832f465c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>ba54cb53-da54-405c-9659-764afa873e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rocket-lazyload</name>
      <type>Main</type>
      <value>fitvidscompatible</value>
      <webElementGuid>213cfa45-fbbd-4ada-8004-c248ae8f1f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://book.appointedd.com/app/638e11d5802579cfe10684e0</value>
      <webElementGuid>dea654af-826b-4855-950a-2b7f0808b462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>49e024ec-3626-47f8-a701-de4032721e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fluentform_24&quot;)/fieldset[1]/div[@class=&quot;ff-el-group&quot;]/iframe[@class=&quot;shortcode_iframe entered lazyloaded&quot;]</value>
      <webElementGuid>af899ee9-c681-45b5-af3c-b1249db44017</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fluentform_24']/fieldset/div/iframe</value>
      <webElementGuid>aab321cf-497b-4750-9589-5bd52283ad6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e51a4951-f9b7-4306-adfa-9e2f02b5c6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://book.appointedd.com/app/638e11d5802579cfe10684e0']</value>
      <webElementGuid>f2c04bce-5af0-4aec-b428-deb8905b283b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
