<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_phone_1</name>
   <tag></tag>
   <elementGuidId>37946880-4188-417c-a668-7042c2581221</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ff_20_2_phone_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ff_20_2_phone_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ed8dcb6-069c-41d9-85fc-df990731beea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone_1</value>
      <webElementGuid>1466b630-35be-4046-9f9c-1fd974f6e886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-el-form-control ff-el-phone</value>
      <webElementGuid>1a61497a-12bb-4cfc-becf-98c7ae20d50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>6f598172-eb73-43d6-9962-5c54d704ceed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>phone_1</value>
      <webElementGuid>acc0e6ab-5b82-4fff-83d3-ddfcd3e7cd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ff_20_2_phone_1</value>
      <webElementGuid>f1088758-d9cc-49d8-acce-ce6f4905ffae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>1f77ed7b-8ed7-43ff-aef6-170dd91f5e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d0e6516e-efcd-4cca-859a-e8a0055ea2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5b7ac035-2efe-4a52-a7aa-4bb9cea4e3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ff_20_2_phone_1&quot;)</value>
      <webElementGuid>42edaac1-21be-442b-b627-420a3f4aa2af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ff_20_2_phone_1']</value>
      <webElementGuid>7bba86c3-3760-4dab-8140-9c04e716b20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fluentform_20']/fieldset/div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>6542c7a8-a10d-4ad8-8595-72a1449c27b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>3aa233a5-6535-4528-aca7-0b59c8c422a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'phone_1' and @type = 'tel' and @id = 'ff_20_2_phone_1']</value>
      <webElementGuid>e49ea529-1fe9-462c-87dc-00ba8a4b4732</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
