<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Name</name>
   <tag></tag>
   <elementGuidId>4d3f2bff-47b0-4941-be5d-a5591a60616d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='fluentform_20']/fieldset/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ce88ac1-32e1-47de-ae37-330f51a98876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-t-cell </value>
      <webElementGuid>a84169af-3656-4bbe-9cda-34ec3e7faa76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>ce1df118-957b-411f-b4ed-80f4654e6b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fluentform_20&quot;)/fieldset[1]/div[@class=&quot;ff-t-container ff-column-container ff_columns_total_2&quot;]/div[@class=&quot;ff-t-cell ff-t-column-1&quot;]/div[@class=&quot;ff-field_container ff-name-field-wrapper&quot;]/div[@class=&quot;ff-t-container&quot;]/div[@class=&quot;ff-t-cell&quot;]</value>
      <webElementGuid>a04aba79-0e04-42c8-a536-dd14e25211ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fluentform_20']/fieldset/div/div/div/div/div</value>
      <webElementGuid>4b355023-d1a1-4e12-85b4-76aebba6bbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div[2]/div/div/form/fieldset/div/div/div/div/div</value>
      <webElementGuid>dfbe4d71-f989-41c4-8713-767411a0f5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Name' or . = 'Name')]</value>
      <webElementGuid>5330d356-1e2d-4d3c-89d1-c652f233d389</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
