<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_phone_2</name>
   <tag></tag>
   <elementGuidId>77aeaf65-b561-47b1-8576-2c617c922c66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ff_20_2_phone_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ff_20_2_phone_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fec2fe3c-7c2f-4a7a-a206-9f6f768fb9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone_2</value>
      <webElementGuid>848fa444-ffb2-45b1-9810-22ecce424eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-el-form-control ff-el-phone</value>
      <webElementGuid>d747b46b-4b8e-423f-b116-5f9d39eaa735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>dfa9493a-0bb8-4a8e-bcc4-84e1b40eb383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>phone_2</value>
      <webElementGuid>10e8538f-52ff-4afb-9a6f-b9ea7700059a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ff_20_2_phone_2</value>
      <webElementGuid>4a287bee-d34f-41fc-ba72-0daf4fd530b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>0b8bf92a-aec7-43c2-93ef-7a7d619420a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a9ede596-64cd-40d1-852d-4cef1f9440d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>92cbf32c-e036-4ece-aef0-27e3f29bc8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ff_20_2_phone_2&quot;)</value>
      <webElementGuid>fb12b849-d694-4b93-82cf-61816f1e33c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ff_20_2_phone_2']</value>
      <webElementGuid>d8d801cd-865b-4585-8009-4a02c19498c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fluentform_20']/fieldset/div[3]/div/div/div[2]/input</value>
      <webElementGuid>eaf9759d-fcd3-4b29-b47b-7b018a8ebdce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/input</value>
      <webElementGuid>c379663a-5334-42ec-9052-c72691129050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'phone_2' and @type = 'tel' and @id = 'ff_20_2_phone_2']</value>
      <webElementGuid>7e6d694c-aad9-41d5-99d0-ff0a5889cab0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
