<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm</name>
   <tag></tag>
   <elementGuidId>62fc2e96-9859-49a4-bd63-9076c7367a09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ap-button.btn-medium.confirm-bookings-submit-button.ng-binding.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>789ab4da-a2a8-48b7-aead-ca749ee3966a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ap-button btn-medium confirm-bookings-submit-button ng-binding ng-scope</value>
      <webElementGuid>78b39f8b-76e1-4db3-a32f-601ad39c1d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>confirmBookings()</value>
      <webElementGuid>b340c3f0-a920-490d-a85d-422e0c799a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>guestDetails.$invalid</value>
      <webElementGuid>4e6a20e6-53b8-46ca-8efa-88cceb00b990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!paymentRequired</value>
      <webElementGuid>99630817-4fb7-4550-96cf-bf860bce8bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						Confirm
					</value>
      <webElementGuid>053a5c3d-f72a-4619-afe3-728595dcd23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[1]/span[@class=&quot;ng-scope&quot;]/ap-booking-app[@class=&quot;ng-scope&quot;]/div[@class=&quot;ap-ba-wrapper ng-scope embedded&quot;]/div[@class=&quot;ap-ba-container with-footer&quot;]/div[@class=&quot;ap-ba-content-wrapper&quot;]/div[@class=&quot;ap-ba-main-section&quot;]/div[@class=&quot;ap-ba-content&quot;]/ap-booking-app-step-confirm[@class=&quot;ap-ba-step-container ng-isolate-scope&quot;]/div[@class=&quot;ap-ba-step confirm-bookings-container&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;confirm-bookings-footer footer-non-multibooking-mode&quot;]/div[@class=&quot;confirm-bookings-buttons&quot;]/span[@class=&quot;confirm-bookings-submit-buttons-click-mask&quot;]/button[@class=&quot;ap-button btn-medium confirm-bookings-submit-button ng-binding ng-scope&quot;]</value>
      <webElementGuid>c4e7b37c-177e-4499-8193-5420a6cdb95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Microsoft Dynamics 365 Business Centra_364156/iframe_shortcode_iframe entered lazyloaded</value>
      <webElementGuid>b2b1d5a1-115c-4c85-834c-910868dd84c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>8490e6ed-018e-425f-9be1-0344da110c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
						Confirm
					' or . = '
						Confirm
					')]</value>
      <webElementGuid>b05d5046-86fa-4473-90ed-3566333ef89a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
