<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_shortcode_iframe entered lazyloaded</name>
   <tag></tag>
   <elementGuidId>26d230f6-1888-473e-ab9d-cb61b288d4a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='fluentform_24']/fieldset/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.shortcode_iframe.entered.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>124ffcd7-87b6-4da3-9c36-3688f1e31847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>d2c844af-02cb-4da6-b05e-c78c6522258c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>21723102-2105-4e83-abd7-c732db54d9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shortcode_iframe entered lazyloaded</value>
      <webElementGuid>197c6984-e9f5-49c5-bd9d-e35d375bfa1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://book.appointedd.com/app/638e11d5802579cfe10684e0</value>
      <webElementGuid>25bc9bb8-1351-4429-bbd5-5452cf858d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>13663eea-77ed-4943-97e4-b03048441719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>2f768f65-e132-4827-8f3e-9770dc5360bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rocket-lazyload</name>
      <type>Main</type>
      <value>fitvidscompatible</value>
      <webElementGuid>436997e1-f05a-44f1-9382-373822129657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://book.appointedd.com/app/638e11d5802579cfe10684e0</value>
      <webElementGuid>6a28d9cd-fa5a-4858-ab2f-a0b0bfb9cd09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>baf98b79-cbb9-4ccd-beef-8f92c2b96a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fluentform_24&quot;)/fieldset[1]/div[@class=&quot;ff-el-group&quot;]/iframe[@class=&quot;shortcode_iframe entered lazyloaded&quot;]</value>
      <webElementGuid>50e7af29-d679-4d8e-a0ae-5bef1c8f4d52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fluentform_24']/fieldset/div/iframe</value>
      <webElementGuid>9457c6cf-c831-42cb-a09a-565a36fb2d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>37ad59da-89bf-45c6-a144-32280b03e5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://book.appointedd.com/app/638e11d5802579cfe10684e0']</value>
      <webElementGuid>c71f723d-0074-4198-9636-9d47d23564ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
