<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_shortcode_iframe entered lazyloaded</name>
   <tag></tag>
   <elementGuidId>26d230f6-1888-473e-ab9d-cb61b288d4a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='fluentform_24']/fieldset/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.shortcode_iframe.entered.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>853adc42-21b1-478b-adc8-70b918661497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>f9112e28-1164-4b02-b754-e86ebee37dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>76545634-2deb-4d2b-9916-8a21c6d5adcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shortcode_iframe entered lazyloaded</value>
      <webElementGuid>c81ecc02-b489-4d2f-b032-97134a833964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://book.appointedd.com/app/638e11d5802579cfe10684e0</value>
      <webElementGuid>b7980d96-17dd-4879-9da1-36cfa3451279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>1dcbd79f-6617-41ca-9001-00c6ed2b811c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>62e9b5dd-8c54-43e7-8ffa-43e7fd52fc2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rocket-lazyload</name>
      <type>Main</type>
      <value>fitvidscompatible</value>
      <webElementGuid>7815a918-5e22-481e-9855-263e09e92b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://book.appointedd.com/app/638e11d5802579cfe10684e0</value>
      <webElementGuid>a75eaaf1-bfbc-4c52-8535-6ae9ee8b6e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>04794b48-02c2-4698-8f97-18aadff65c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fluentform_24&quot;)/fieldset[1]/div[@class=&quot;ff-el-group&quot;]/iframe[@class=&quot;shortcode_iframe entered lazyloaded&quot;]</value>
      <webElementGuid>986ce8bd-56c0-416e-a817-699a1ca2347e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fluentform_24']/fieldset/div/iframe</value>
      <webElementGuid>ac990d8c-28d9-4a24-85b8-cb68a157ba1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>957e6a74-673e-472b-8f93-688c0a31a2e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://book.appointedd.com/app/638e11d5802579cfe10684e0']</value>
      <webElementGuid>9a4fa77b-dfda-4db3-91ed-877c910ace9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
