<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mobile</name>
   <tag></tag>
   <elementGuidId>375c6d06-53e0-4e12-ba9d-0c536fea58ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mobile']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mobile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e3ed64f-de3d-4e6f-9af3-72ccf608a01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>48b2657e-05b4-4f39-b359-8e7835bf6be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ap-ba-error-input ng-pristine ng-untouched ng-valid ng-empty ng-valid-ng-intl-tel-input ng-valid-required</value>
      <webElementGuid>76a81ff6-6028-4b7d-884d-39fcc8bfd4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>8eca8d28-b2a7-4892-a0e8-11b175b88807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobile</value>
      <webElementGuid>ef273583-9dac-4237-a981-184886e49b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobile</value>
      <webElementGuid>f5f3bb44-28ce-4ad5-9e6d-bad4ce13fb32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>customer.profile.mobile</value>
      <webElementGuid>c76aa9d4-8a20-45ea-abc7-17b175022fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>mobileRequired</value>
      <webElementGuid>f48b4655-050f-494f-85cc-4223f72f7dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e5cb2d51-c0cc-4d7a-8eed-a0214a2a968b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile&quot;)</value>
      <webElementGuid>7b5ce7ed-c8c3-434d-a558-091daa5388d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Microsoft Dynamics 365 Business Centra_364156/iframe_shortcode_iframe entered lazyloaded</value>
      <webElementGuid>8129411a-631b-40d2-a501-4862627c2bdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mobile']</value>
      <webElementGuid>60f0be71-b855-4ab3-8e29-1b7dd534509e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='guestDetails']/div[4]/span/div/input</value>
      <webElementGuid>7a44e144-6684-4b77-a092-6340d423952e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>8caea1ac-13f1-42fd-ac1a-5f48045877a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'mobile' and @id = 'mobile']</value>
      <webElementGuid>238bfb58-b009-46ec-b4bd-878a29ce5214</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
