<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_input_text</name>
   <tag></tag>
   <elementGuidId>5e073117-2418-408a-b7da-61449e02cb14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ff_1_input_text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ff_1_input_text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d355ebc-0943-4fa8-90fc-b4dfd36f77bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54f9c609-8580-485e-b185-da8afeafa17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_text</value>
      <webElementGuid>a3d10dc3-1c9d-4d74-b1bb-6750354a572f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-el-form-control</value>
      <webElementGuid>0541a5f1-6e36-47a7-971b-ab7d73a1aa83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>input_text</value>
      <webElementGuid>81ce97c1-37db-4abf-b0d4-8c80de3fc3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ff_1_input_text</value>
      <webElementGuid>19a60656-f87b-439d-8975-bbafc5661d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c3a993d5-7f68-4ef5-9197-9d90e47e7799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3108c1b4-e070-4711-8e53-acd227695f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ff_1_input_text&quot;)</value>
      <webElementGuid>e5290857-9ce7-42a5-9e22-bc965acb51d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ff_1_input_text']</value>
      <webElementGuid>6e895dd7-f977-4d8f-878c-3eea37ca4f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fluentform_1']/fieldset/div/div[2]/input</value>
      <webElementGuid>b5f5644f-382b-460e-bc1f-559a25ac910d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5e688f3d-176a-46a1-af0f-33ddda53ed87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'input_text' and @id = 'ff_1_input_text']</value>
      <webElementGuid>e54f83e6-f1f4-45f5-bc41-1c43191d7018</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
