<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_input_text_1</name>
   <tag></tag>
   <elementGuidId>d2d78a4f-b788-4b13-9344-b149405793ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ff_1_input_text_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ff_1_input_text_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>373bd45d-cf11-4700-9501-5ed38590c546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c1e44eca-3516-44cb-ae36-f549ed135286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_text_1</value>
      <webElementGuid>8af22288-8722-44a7-b705-6f153dd068c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-el-form-control</value>
      <webElementGuid>69fd52a9-a250-41a7-b511-c18b80ebf65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>input_text_1</value>
      <webElementGuid>d7188f32-198e-4a44-ba06-efac6e7cc79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ff_1_input_text_1</value>
      <webElementGuid>9854713c-f80c-406b-8158-0163f435dce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>df927ec1-9081-4970-878d-f935991ea42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1c3171ac-e52c-4bf5-bf91-a09f947ceace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ff_1_input_text_1&quot;)</value>
      <webElementGuid>3c3dc7f4-701d-441c-af82-055e7399b1b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ff_1_input_text_1']</value>
      <webElementGuid>704c6f85-cb91-4919-9429-f9f1d2e66168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fluentform_1']/fieldset/div[2]/div[2]/input</value>
      <webElementGuid>f96cbac1-785d-4de8-9b9d-d23951a5148b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>0a0904c5-c6f3-41e5-b585-0123f7e30673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'input_text_1' and @id = 'ff_1_input_text_1']</value>
      <webElementGuid>7f6f4273-5ce9-4ac5-bf8c-35a48fb7d4a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
